name: Build Dauladailuc Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build project
      run: gradle build

    - name: Upload mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dauladailuc-Mod
        path: build/libs/*.jar
