name: Build Dauladailuc Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Find gradlew
      id: find_gradlew
      run: |
        GRADLEW_FILE=$(find . -name gradlew -type f | head -n 1)
        if [ -z "$GRADLEW_FILE" ]; then
          echo "Error: gradlew not found in repo!"
          exit 1
        fi
        echo "GRADLEW_PATH=$GRADLEW_FILE" >> $GITHUB_ENV
        echo "Found gradlew at $GRADLEW_FILE"

    - name: Grant execute permission for gradlew
      run: chmod +x $GRADLEW_PATH

    - name: Build with Gradle
      run: $GRADLEW_PATH build

    - name: Upload mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dauladailuc-Mod
        path: build/libs/*.jar
