name: Build Dauladailuc Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle wrapper
      run: ./gradlew build

    - name: Set artifact name with date and commit SHA
      id: artifact
      run: |
        DATETIME=$(date +'%Y-%m-%d-%H%M')
        echo "ARTIFACT_NAME=Dauladailuc-Mod-${DATETIME}-${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Upload mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: build/libs/*.jar
